[package]
name = "stringsext"
version = "1.3.1"
authors = ["Jens Getreu <getreu@web.de>"]

[dependencies]
#encoding = { git = "https://github.com/lifthrasiir/rust-encoding" }
# use nighly itertools with bugfix: Merge pull request #135 (2. Aug. 2016)
# minimum version is: 0.4.17!
#itertools = { git = "https://github.com/bluss/rust-itertools" }
docopt = "*"
encoding = "*"
itertools = "*"
lazy_static = "*"
memmap = "*"
rand = "*"
rustc-serialize = "*"
scoped_threadpool = "*"
tempdir = "*"
